---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx service is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create index.html according to template
  ansible.builtin.template:
    src: ../templates/index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: reinicia nginx